### ISSUE TITLE
xcvalu carry bit for add+shift operation

### ISSUE THREAD

**Issue by realqhc** [openhwgroup/core-v-sw#262]
https://github.com/llvm/llvm-project/pull/78138#discussion_r1452688437
From the spec there is a carry bit as mentioned in comment above, is this true that the bit is retained after shift operation?

**Comment by pascalgouedo** [comment]
As replied in https://github.com/llvm/llvm-project/pull/78138, there is no carry in RISC-V spec.
And same for intermediate computation result.
